### PR TITLE
Add a Julia filter

### PR DESCRIPTION
**Pull request by jonathan-laurent**
The Julia dataset contains JSON Lines files with extension `.jl` and  large files of auto-generated boilerplate (e.g. wrappers, dumps of large arrays...). This PR implements two filters for the Julia language:

- `julia_filter` reduces the dataset size from 1.75GB to 1.5GB by eliminating JSON files and overly large files, keeping test suites with a limited number of floating point literals.
- `julia_filter_strict` further reduces it to 1GB by using an explicit whitelist of keywords that tests for direct relevance to scientific computing (disabled for now by default).

This PR also adds support for an `HUGGING_FACE_TOKEN` environment variable in `process_source_code` to make it easier to download the `code-stack` dataset from HF.

### CODE REVIEW

**Comment by zhangir-azerbayev** [comment]
Awesome contribution. Ready to merge after addressing my two minor comments.

**Comment by jonathan-laurent** [comment]
@zhangir-azerbayev Thanks! I do not see your two comments though. I am looking at the wrong place?

**Comment by zhangir-azerbayev** [comment]
I see them under the Files changed tab

**Comment by jonathan-laurent** [comment]
Good catch regarding the README. I was always talking about the size of the Julia subset but wrote 175GB instead of 1.75GB. I just fixed this.

Regarding the notebook, I can move the stuff from julia.ipynb to analysis.ipynb indeed, especially since a lot of it is not Julia specific.

**Comment by jonathan-laurent** [comment]
@zhangir-azerbayev I addressed your two comments. Please tell me if I can do anything else.

**Review by zhangir-azerbayev — APPROVED** [review]

**Pull request merged**
