### PR TITLE
Jupyter notebook

### PR DESCRIPTION
**Pull request by wellecks**
Jupyter notebook filtering and processing.

### CODE REVIEW

**Comment by zhangir-azerbayev** [comment]
Would it be possible to delete only the outputs that exceed a certain length threshold? For example, only those shorter than an mnist image.

**Comment by zhangir-azerbayev** [comment]
By the way, when I try to run `process_source_code.py` I'm getting the error `FileNotFoundError: Dataset 'bigcode/the-stack-dedup' doesn't exist on the Hub.`, which is really bizarre. Is this just my machine acting weird?

**Comment by wellecks** [comment]
Re: outputs yes, good idea

For the `FileNotFoundError`, I had to login to huggingface on the command line, since the stack has a layer of security (e.g., we need to accept the terms of use to get access to it, which is linked to our huggingface account)

**Comment by jonathan-laurent** [comment]
Regarding the `FileNotFoundError` error, my Julia filter PR adds support for an `HUGGING_FACE_TOKEN` env variable that allows one to provide a HF authentification token.

**Comment by wellecks** [comment]
@zhangir-azerbayev I switched it to only remove outputs when they include a base64 png string or an exception traceback. Now we're at ~300M tokens.

**Pull request merged**
